# Base configs
baseurl: ""
image_fulls_loc: "/images/fulls"
image_thumbs_loc: "/images/thumbs"
google_analytics: ""

# UI configs
title: "Photography by Alessandro Sebastianelli"
subtitle: ""
author: "Alessandro Sebastianelli"
header:
 title: "Photography"
 subtitle: "by Alessandro Sebastianelli"
footer:
 name: ""
 bio: ""
 github: ""
web_design: ""
social_urls:
  facebook: ""
  twitter: ""
  instagram: ""
  dribbble: ""
  linkedin: ""
  github: ""
